# Sử dụng image Nginx nhẹ
FROM nginx:stable-alpine

# (Tùy chọn) Xóa nội dung mặc định của Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copy toàn bộ file HTML/CSS/JS vào thư mục gốc web của Nginx
COPY . /usr/share/nginx/html

# Mở port 80 cho HTTP
EXPOSE 80

# Khởi động Nginx ở foreground
CMD ["nginx", "-g", "daemon off;"]
